name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    # Otorgar permisos de ejecución al Gradle Wrapper
    - name: Grant execution permissions for Gradle Wrapper
      run: chmod +x ./gradlew

    # Ejecutar las pruebas de Cucumber con la etiqueta @Navego
    - name: Build with Gradle Wrapper
      run: ./gradlew test -Dcucumber.options="--tags @Navego"

  dependency-submission:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    # Genera y envía el gráfico de dependencias para las alertas de Dependabot
    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
